<?php  
  $CACHE=array (
  'site' => 6,
  'site/index' => 6,
  'mingrui-doc' => 20,
  'mingrui-doc/index' => 3,
  'mingrui-doc/create' => 16,
  'mingrui-doc/view' => 1,
  'rest-client' => 3,
  'rest-client/index' => 3,
  'profile' => 1,
  'profile/show' => 1,
  'restsample' => 6,
  'restsample/index' => 1,
  'restsample/index-report' => 5,
  'rest-report' => 1,
  'rest-report/comments' => 1,
  'mingrui-attachment' => 1,
  'mingrui-attachment/index' => 1,
  'orders' => 2,
  'orders/index' => 2,
  'user' => 3,
  'user/index' => 3,
);  ?>